### ISSUE TITLE
add footer for the project

### ISSUE THREAD

**Issue by zabihhaqqani** [zabihhaqqani/First-pull-request#13]
- add my social account 
- https://github.com/zabihhaqqani
- https://www.linkedin.com/in/zabih-haqqani-7ab187191/
- https://twitter.com/zabih01

**Comment by maazbinzafer** [comment]
Please assign this to me.

**Comment by zabihhaqqani** [comment]
Sure assigning it to you.

**Comment by zabihhaqqani** [comment]
add icons if possible

**Comment by minhaj-313** [comment]
Hi I want to contribute in your project please give me some suggestion what can I do for hacktoberfest PR,
Thank You in Advance Sir.

**Comment by zabihhaqqani** [comment]
The changes are already done @minhaj-313

**Comment by minhaj-313** [comment]
> The changes are already done @minhaj-313

is their any other issue
I want to contribute I am new in hacktoberfest

**Comment by zabihhaqqani** [comment]
try to contribute to other repositories in my profile.

**Comment by minhaj-313** [comment]
> try to contribute to other repositories in my profile.

ok Thanks
